TOP=../..
include $(TOP)/configure/CONFIG
DB += $(ASYN)/db/asynRecord.db
DB += ai_average.template
DB += ai.template
DB += ao.template
DB += asynRecord.template
DB += bi_bit.template
DB += bi_word.template
DB += bo_bit.template
DB += bo_word.template
DB += intarray_in.template
DB += intarray_out.template
DB += longin.template
DB += longout.template
DB += mbbiDirect.template
DB += mbboDirect.template
DB += poll_delay.template
DB += statistics.template
include $(TOP)/configure/RULES
